### ISSUE TITLE
Tranfer RserveCLI2 to a repo under an org

### ISSUE THREAD

**Issue by atifaziz** [konne/RserveCLI2#42]
Should we create an org and transfer the RserveCLI2 repo into that org? Very little is lost in terms of ownership but much else is gained in terms of organisation, repos & stability.

**Comment by SurajGupta** [comment]
lets do it.  can you setup the org?

**Comment by SurajGupta** [comment]
hey @atifaziz  - are you still interested in doing this?  I decided that I'm no longer going to maintain this repo.  Are you still actively working on this stuff?  Interested in taking it over?

**Comment by konne** [comment]
maybe later this can be moved to an org, but I see no advantage at the moment so I close this
