### ISSUE TITLE
getting and setting raw data

### ISSUE THREAD

**Issue by mBioWolf** [konne/RserveCLI2#44]
i want to write variables from the rserve directly to a Database, using c# and RserveCLI2. As these variables can be complex (e.g. environments) the Sexp class disrupts them sometimes. As I do not want to get single entries, i wanted to receive the data as a SexpRaw and write the binary stream to the database. later on loading the data i wanted to do this the other way around and read the stream from the mysql server into SexpRaw, send this sexp to rserve and having the original variable back in the environment.
Unfortunately this did not work. Is there a hint how i could solve this?

thanx

**Comment by konne** [comment]
Hi, I see this not as a good practise and will close that.
