### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by memmo77** [konne/RserveCLI2#49]
Hi!
Thank you for your precious work. 
I opened the solution with VS2012 and by compiling I get 133 errors
How can I fix it?
Thank you

**Comment by SurajGupta** [comment]
i'm no longer supporting this project, so perhaps other folks can chime-in.  You might try VS2015 Community edition

**Comment by konne** [comment]
@SurajGupta I really like to maintane the project
Do you like to takeover that project to me?

bye Konrad

**Comment by SurajGupta** [comment]
I'd love to handoff this project!  Let me see if I can make you an admin.

**Comment by SurajGupta** [comment]
@konne - I made you a collaborator.  Were you thinking of some other kind of solution?  I'm not sure what's possible with GitHub - like maybe a project can be fully transferred to someone else.  Is that what you were thinking?

**Comment by konne** [comment]
you can transfer it under the settings in the project, very low down -> 
![grafik](https://user-images.githubusercontent.com/1100969/29273111-376f2b20-8103-11e7-9ba5-7032c1fd0518.png)

**Comment by konne** [comment]
@SurajGupta I wrote you my skype per email name so that we can discuss this private

**Comment by SurajGupta** [comment]
I just requested the transfer.

**Comment by konne** [comment]
@memmo77 I will check this the next days
